baseurl: https://rakuishi.com/
languageCode: ja
title: rakuishi.com
author: rakuishi
metadataformat: yaml
preservetaxonomynames: true

related: 
  indices: [{name: categories, weight: 100}]

sitemap:
  changefreq: daily
  priority: 0.9
  filename: sitemap.xml